"""initial schema

Revision ID: b059e4f29203
Revises: 
Create Date: 2026-02-27 18:13:45.218986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b059e4f29203'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_ips',
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('ip')
    )
    with op.batch_alter_table('blocked_ips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocked_ips_blocked_at'), ['blocked_at'], unique=False)

    op.create_table('mitigation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mitigation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mitigation_events_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_mitigation_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('traffic_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('request_rate', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('payload_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traffic_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_logs_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_logs_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_traffic_logs_ip'))

    op.drop_table('traffic_logs')
    with op.batch_alter_table('mitigation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mitigation_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_mitigation_events_ip'))

    op.drop_table('mitigation_events')
    with op.batch_alter_table('blocked_ips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocked_ips_blocked_at'))

    op.drop_table('blocked_ips')
    # ### end Alembic commands ###
